# **Numpy**
**Question** **1**

In [104]:
import numpy as np

In [105]:
arr = np.random.randint(10,50,size=(20))
print(arr)

[36 10 10 32 24 47 37 31 26 26 14 27 31 27 31 30 40 23 35 32]


In [106]:
mean = np.mean(arr)
print("mean=", mean)

mean= 28.45


In [107]:
std = np.std(arr)
print("std=", std)

std= 9.091067044082338


**Question 2**

In [42]:
arr1 = np.random.rand(6,5)
print ("\narr1=", arr1)


arr1= [[0.96278793 0.77471005 0.70039793 0.83610957 0.14670119]
 [0.07245099 0.37379275 0.54503186 0.66214476 0.33392176]
 [0.29423367 0.12065125 0.37986971 0.07878199 0.96292306]
 [0.29125096 0.93702581 0.74565641 0.22870429 0.40277565]
 [0.76057462 0.26826485 0.73512416 0.26609062 0.51245788]
 [0.8878356  0.698793   0.74326871 0.91346475 0.7201737 ]]


In [ ]:
arr1.reshape(5,6)

array([[0.58275567, 0.85635514, 0.71943591, 0.14182666, 0.25140395,
        0.04920831],
       [0.60231857, 0.9549849 , 0.18956486, 0.61739078, 0.0354625 ,
        0.73129012],
       [0.11462223, 0.70439404, 0.62253094, 0.2767939 , 0.26629936,
        0.6818235 ],
       [0.44896644, 0.83874137, 0.23404887, 0.25256953, 0.15311099,
        0.42086063],
       [0.08117754, 0.66071981, 0.31825928, 0.69972443, 0.42527302,
        0.71169686]])

**Question 3**

In [43]:
arr2 = np.arange(1,26).reshape(5,5)
print("\narr2", arr2)
arr2[1:,1:4]


arr2 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

**Question 4**

In [44]:
A = np.random.randint(1,100,size=10)
B = np.random.randint(1,100,size=10)
print("A", A)
print("B", B)
addition = A+B
result = (A+B)*2
print("\naddition=", addition)
print("\nresult=", result)


A [14 94 78  6 75 46 54 77 84 25]
B [62 26 99 76 34 73 53 56 36 56]

addition= [ 76 120 177  82 109 119 107 133 120  81]

result= [152 240 354 164 218 238 214 266 240 162]


**Question 5**

In [ ]:
A2 = np.random.randint(1,11,size=(3,4))
B2 = np.array([1, 2, 3, 4])
print("\nA2=", A2)
print("\nB2=", B2)
result = A2+B2
print("\nresult=", result)



A2= [[5 7 3 9]
 [3 2 3 2]
 [9 4 9 1]]

B2= [1 2 3 4]

result= [[ 6  9  6 13]
 [ 4  4  6  6]
 [10  6 12  5]]


Broadcasting in NumPy allows arithmetic operations between arrays of different shapes. In the above case, the 1D array B is broadcasted to match the shape of the 2D array A so that the addition operation can be performed element-wise.
NumPy compares a set of array dimensions from right to left.
Every set of dimensions must be compatible with the arrays to be broadcastable. A set of dimension lengths is compatible when
*   one of them has a length of 1
*   or they are equal




**Question 6**

In [108]:
arr3 = np.random.randint(1,100,size=(3,3))
arr3


array([[79, 38,  3],
       [81, 39, 54],
       [67, 81, 58]])

In [109]:
sum=np.sum(arr3, axis=1)
print("sum=", sum)

sum= [120 174 206]


In [111]:
np.argmax(sum)

2

**Question** **7**

In [50]:
A1 = np.random.randint(1,100,size=(2,2))
B1 = np.random.randint(1,100,size=(2,2))
print("\nA1=", A1)
print("\nB1=", B1)
np.dot(A1,B1)



A1= [[14  8]
 [94 43]]

B1= [[88 45]
 [39 38]]


array([[1544,  934],
       [9949, 5864]])

**Question 8**

In [51]:
arr4 = np.random.randint(1,51,size=(6,6))
print("arr4=",arr4)
greater_than_25=arr4[arr4>25]
print("\ngreater_than_25=", greater_than_25)

arr4= [[32  2 48 47 36 19]
 [48 30 21 32 22 44]
 [47 34 31 33 17  1]
 [48 27  5  8 37 28]
 [29 28  1 46 16 30]
 [12 24 29 34 22 10]]

greater_than_25= [32 48 47 36 48 30 32 44 47 34 31 33 48 27 37 28 29 28 46 30 29 34]


**Question 9**

In [52]:
arr5 = np.random.rand(5,5)
print("\narr5=",arr5)
median_col = np.median(arr5, axis=0)
print("\nmedian_col=", median_col)
median_row = np.median(arr5, axis=1)
print("\nmedian_row=", median_row)
var_col = np.var(arr5, axis=0)
print("\nvar_col=", var_col)
var_row = np.var(arr5, axis=1)
print("\nvar_row=",var_row)


arr5= [[0.20241954 0.73753371 0.90173215 0.00442371 0.96179289]
 [0.63341994 0.90031684 0.89376997 0.31527821 0.54813455]
 [0.57675918 0.19999607 0.13964002 0.63245551 0.6971298 ]
 [0.29146241 0.57413515 0.8916505  0.22016592 0.82446712]
 [0.37857779 0.49048423 0.46433649 0.34384888 0.49117516]]

median_col= [0.37857779 0.57413515 0.8916505  0.31527821 0.6971298 ]

median_row= [0.73753371 0.63341994 0.57675918 0.57413515 0.46433649]

var_col= [0.02712804 0.0559738  0.09515755 0.04127387 0.03012074]

var_row= [0.14925058 0.04888752 0.05385062 0.07354673 0.00371562]


**Question 10**

In [98]:
arr6 = np.random.randint(1,11,size=(3,3))
print("arr6=",arr6)

arr6= [[ 3  6  1]
 [ 1  8  8]
 [10  9  2]]


In [ ]:
sub = arr6-2
print("sub=", sub)

sub= [[ 5  8 -1]
 [-1  1  0]
 [ 7  0  8]]


In [99]:
square = arr6*arr6
print("square=", square)

square= [[  9  36   1]
 [  1  64  64]
 [100  81   4]]


In [100]:
reciprocal = np.reciprocal(arr6)
print("reciprocal=", reciprocal)

reciprocal= [[0 0 1]
 [1 0 0]
 [0 0 0]]


# **Pandas**

**Question** **1**

In [ ]:
import pandas as pd

In [10]:
df = pd.read_csv("/content/auto-mpg (1).csv")


**question 1.1**

In [28]:
df.head(10)

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   
5  15.0          8         429.0        198    4341          10.0          70   
6  14.0          8         454.0        220    4354           9.0          70   
7  14.0          8         440.0        215    4312           8.5          70   
8  14.0          8         455.0        225    4425          10.0          70   
9  15.0          8         390.0        190    3850           8.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino  
5       1           ford galaxie 500  
6       1           chevrolet impala  
7       1          plymouth fury iii  
8       1           pontiac catalina  
9       1         amc ambassador dpl

**question 1.2**

In [101]:
df.shape

(398, 11)

**question** **1.3**

In [102]:
df.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  392.000000   398.000000   
mean    23.514573    5.454774    193.425879  104.469388  2970.424623   
std      7.815984    1.701004    104.269838   38.491160   846.841774   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.500000    4.000000    104.250000   75.000000  2223.750000   
50%     23.000000    4.000000    148.500000   93.500000  2803.500000   
75%     29.000000    8.000000    262.000000  126.000000  3608.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model year      origin  power_to_weight_ratio  \
count    398.000000  398.000000  398.000000             392.000000   
mean      15.568090   76.010050    1.572864               0.034833   
std        2.757689    3.697627    0.802055               0.005935   
min        8.000000   70.000000    1.000000               0.020557   
25%       13.825000   73.000000    1.000000               0.030820   
50%       15.500000   76.000000    1.000000               0.034285   
75%       17.175000   79.000000    2.000000               0.038082   
max       24.800000   82.000000    3.000000               0.072910   

       performance_score  
count         398.000000  
mean            0.148889  
std             0.094161  
min             0.026117  
25%             0.073722  
50%             0.129122  
75%             0.209431  
max             0.508169

**Question 2**

In [12]:
df[(df["weight"] < 3000) & (df["model year"] == 75)][["car name", "model year"]]

car name  model year
167     toyota corolla          75
168         ford pinto          75
169        amc gremlin          75
170      pontiac astro          75
171      toyota corona          75
172  volkswagen dasher          75
173         datsun 710          75
174         ford pinto          75
175  volkswagen rabbit          75
177         audi 100ls          75
178        peugeot 504          75
179        volvo 244dl          75
180          saab 99le          75
181   honda civic cvcc          75

**Question 3**

In [16]:
print("Missing values in the dataset:")
print(df.isnull().sum())


Missing values in the dataset:
mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64


In [20]:
horsepower_median = (df["horsepower"].median)
print(horsepower_median)


<bound method Series.median of 0      130
1      165
2      150
3      150
4      140
      ... 
393     86
394     52
395     84
396     79
397     82
Name: horsepower, Length: 398, dtype: object>


In [21]:
df["horsepower"].fillna(horsepower_median, inplace=True)

In [26]:
print("\nDataset after replacing missing values in 'horsepower':")
print(df)


Dataset after replacing missing values in 'horsepower':
      mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet ch

**Question 4**

In [41]:
df['power_to_weight_ratio'] = df['horsepower'] / df['weight']
print(df)

      mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model year  origin                   car name  power_to_weight_ratio  
0            70       1  chevrolet chevelle malibu         

**Question** **5**

In [58]:
mean_mpg_origin = df.groupby('origin')['mpg'].mean()
print(mean_mpg_origin)

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64


**Question 6**

In [63]:
sort = df.sort_values(by="mpg", ascending=False)
top_10_cars = sort.head(10)
print(top_10_cars)

      mpg  cylinders  displacement  horsepower  weight  acceleration  \
322  46.6          4          86.0        65.0    2110          17.9   
329  44.6          4          91.0        67.0    1850          13.8   
325  44.3          4          90.0        48.0    2085          21.7   
394  44.0          4          97.0        52.0    2130          24.6   
326  43.4          4          90.0        48.0    2335          23.7   
244  43.1          4          90.0        48.0    1985          21.5   
309  41.5          4          98.0        76.0    2144          14.7   
330  40.9          4          85.0         NaN    1835          17.3   
324  40.8          4          85.0        65.0    2110          19.2   
247  39.4          4          85.0        70.0    2070          18.6   

     model year  origin                         car name  \
322          80       3                        mazda glc   
329          80       3              honda civic 1500 gl   
325          80       2    

**Question 7**

In [62]:
def performance_score(row):
    return row["mpg"] * row["acceleration"] / row["weight"]
df["performance_score"] = df.apply(performance_score, axis=1)
print(df)


      mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model year  origin                   car name  power_to_weight_ratio  \
0            70       1  chevrolet chevelle malibu        

**Question 8**

In [87]:
summary = df.groupby("model year").agg({
    "mpg": "mean",
    "horsepower": "mean",
    "weight": "mean"
})
print(summary)

                  mpg  horsepower       weight
model year                                    
70          17.689655  147.827586  3372.793103
71          21.250000  107.037037  2995.428571
72          18.714286  120.178571  3237.714286
73          17.100000  130.475000  3419.025000
74          22.703704   94.230769  2877.925926
75          20.266667  101.066667  3176.800000
76          21.573529  101.117647  3078.735294
77          23.375000  105.071429  2997.357143
78          24.061111   99.694444  2861.805556
79          25.093103  101.206897  3055.344828
80          33.696552   77.481481  2436.655172
81          30.334483   81.035714  2522.931034
82          31.709677   81.466667  2453.548387


**Question 9**

In [90]:
high_mpg_cars = df[df["mpg"] > 30]
high_mpg_cars_subset = high_mpg_cars[["mpg", "cylinders", "horsepower", "weight"]]
high_mpg_cars_subset.to_csv("high_mpg_cars.csv")
print(high_mpg_cars_subset)


      mpg  cylinders  horsepower  weight
53   31.0          4        65.0    1773
54   35.0          4        69.0    1613
129  31.0          4        67.0    1950
131  32.0          4        65.0    1836
144  31.0          4        52.0    1649
..    ...        ...         ...     ...
390  32.0          4        96.0    2665
391  36.0          4        84.0    2370
394  44.0          4        52.0    2130
395  32.0          4        84.0    2295
397  31.0          4        82.0    2720

[85 rows x 4 columns]


**Question 10**


**10.1**

In [94]:
Q1 = df["mpg"].quantile(0.25)
Q3 = df["mpg"].quantile(0.75)
IQR = Q3 - Q1
print("\nIQR:", IQR)


IQR: 11.5


**10.2**

In [95]:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print("\nLower Bound:", lower_bound)
print("\nUpper Bound:",upper_bound)


Lower Bound: 0.25

Upper Bound: 46.25


**10.3**

In [97]:
outliers = df[(df["mpg"] < lower_bound) | (df["mpg"] > upper_bound)]
outliers_df = outliers[['car name', 'mpg', 'model year']]
print("Outliers in the 'mpg' column:")
print(outliers_df)

Outliers in the 'mpg' column:
      car name   mpg  model year
322  mazda glc  46.6          80
